[site]
title = '傅小黑的闲言碎语'
subtitle = '傅小黑的闲言碎语'
description = '傅小黑的闲言碎语，记录生活中的胡说八道'
keywords = [
    '傅小黑',
    'blog',
    '博客',
    '个人站点'
]
language = 'zh-CN'
author = 'fuxiaohei'

[url]
base = 'https://fuxiaohei.me'
root = '/'
post_link_format = '/:year/:month/:day/:slug'
post_page_format = '/page/:page'
per_page_size = 10
tag_link_format = '/tag/:tag'
tag_page_format = '/tag/:tag/page/:page'

[directory]
source = 'source'
output = 'dist'
themes = 'themes'
assets = ['assets']

[theme]
name = 'pugo-rs'
index_template = 'posts.hbs'
assets_dir = ['static']

[[nav]]
name = '首页'
url = '/'

[[nav]]
name = '归档'
url = '/archives/'

[[nav]]
name = '好友'
url = '/friends'

[[nav]]
name = '关于'
url = '/about'

[author.fuxiaohei]
name = '傅小黑'
email = 'fuxiaohei@vip.qq.com'
website = 'https://fuxiaohei.me'
bio = 'Backend Developer'
avatar = '/assets/avatar.jpeg'
use_gravatar = false

[author.fuxiaohei.social]
github = "https://github.com/fuxiaohei"
twitter = "https://twitter.com/fuxiaohei"
weibo = "https://weibo.com/fuxiaohei"
